# Options: qlearning
Algorithm: qlearning

# Options: f1
Agent: f1

# Options: train, test
Method: train 

# Hyperparams QLearning
qlearning: 
  alpha: 0.4
  gamma: 0.9

# Options: simple_circuit
Model: simple_circuit

simple_circuit:
  	

